# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '酒店信息.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowHotel(object):
    def setupUi(self, MainWindowHotel):
        MainWindowHotel.setObjectName("MainWindowHotel")
        MainWindowHotel.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowHotel)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 72, 15))
        self.label.setObjectName("label")
        self.lineEditSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch.setGeometry(QtCore.QRect(320, 60, 113, 21))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setGeometry(QtCore.QRect(550, 50, 40, 40))
        self.pushButtonSearch.setText("")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.tableWidgetResults = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetResults.setGeometry(QtCore.QRect(110, 140, 561, 241))
        self.tableWidgetResults.setObjectName("tableWidgetResults")
        self.tableWidgetResults.setColumnCount(7)
        self.tableWidgetResults.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(6, item)
        self.pushButtonRegister = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(150, 450, 40, 40))
        self.pushButtonRegister.setText("")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 110, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 510, 72, 15))
        self.label_3.setObjectName("label_3")
        MainWindowHotel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowHotel)
        self.statusbar.setObjectName("statusbar")
        MainWindowHotel.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowHotel)
        QtCore.QMetaObject.connectSlotsByName(MainWindowHotel)

    def retranslateUi(self, MainWindowHotel):
        _translate = QtCore.QCoreApplication.translate
        MainWindowHotel.setWindowTitle(_translate("MainWindowHotel", "酒店信息"))
        self.label.setText(_translate("MainWindowHotel", "所在城市"))
        item = self.tableWidgetResults.verticalHeaderItem(0)
        item.setText(_translate("MainWindowHotel", "1"))
        item = self.tableWidgetResults.verticalHeaderItem(1)
        item.setText(_translate("MainWindowHotel", "2"))
        item = self.tableWidgetResults.verticalHeaderItem(2)
        item.setText(_translate("MainWindowHotel", "3"))
        item = self.tableWidgetResults.verticalHeaderItem(3)
        item.setText(_translate("MainWindowHotel", "4"))
        item = self.tableWidgetResults.verticalHeaderItem(4)
        item.setText(_translate("MainWindowHotel", "5"))
        item = self.tableWidgetResults.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowHotel", "编号"))
        item = self.tableWidgetResults.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowHotel", "名称"))
        item = self.tableWidgetResults.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowHotel", "电话"))
        item = self.tableWidgetResults.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowHotel", "城市"))
        item = self.tableWidgetResults.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowHotel", "房间类型"))
        item = self.tableWidgetResults.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowHotel", "剩余房间"))
        item = self.tableWidgetResults.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowHotel", "价格"))
        self.label_2.setText(_translate("MainWindowHotel", "查询"))
        self.label_3.setText(_translate("MainWindowHotel", "添加"))

