# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '员工操作界面.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_operationWindow(object):
    def setupUi(self, operationWindow):
        operationWindow.setObjectName("operationWindow")
        operationWindow.resize(872, 703)
        self.centralwidget = QtWidgets.QWidget(operationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonCustmerInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCustmerInfo.setGeometry(QtCore.QRect(370, 60, 128, 128))
        self.pushButtonCustmerInfo.setText("")
        self.pushButtonCustmerInfo.setObjectName("pushButtonCustmerInfo")
        self.labelCustmerInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo.setGeometry(QtCore.QRect(390, 200, 81, 31))
        self.labelCustmerInfo.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo.setObjectName("labelCustmerInfo")
        self.pushButtonOrderDetail = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOrderDetail.setGeometry(QtCore.QRect(630, 60, 128, 128))
        self.pushButtonOrderDetail.setText("")
        self.pushButtonOrderDetail.setObjectName("pushButtonOrderDetail")
        self.labelCustmerInfo_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo_2.setGeometry(QtCore.QRect(650, 200, 81, 31))
        self.labelCustmerInfo_2.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo_2.setObjectName("labelCustmerInfo_2")
        self.labelCustmerInfo_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo_3.setGeometry(QtCore.QRect(380, 630, 111, 31))
        self.labelCustmerInfo_3.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo_3.setObjectName("labelCustmerInfo_3")
        self.labelCustmerInfo_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo_4.setGeometry(QtCore.QRect(390, 410, 81, 31))
        self.labelCustmerInfo_4.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo_4.setObjectName("labelCustmerInfo_4")
        self.labelCustmerInfo_5 = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo_5.setGeometry(QtCore.QRect(650, 410, 81, 31))
        self.labelCustmerInfo_5.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo_5.setObjectName("labelCustmerInfo_5")
        self.labelCustmerInfo_6 = QtWidgets.QLabel(self.centralwidget)
        self.labelCustmerInfo_6.setGeometry(QtCore.QRect(650, 630, 81, 31))
        self.labelCustmerInfo_6.setStyleSheet("font: 12pt \"新宋体\";")
        self.labelCustmerInfo_6.setObjectName("labelCustmerInfo_6")
        self.pushButtonCarLib = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCarLib.setGeometry(QtCore.QRect(370, 270, 128, 128))
        self.pushButtonCarLib.setText("")
        self.pushButtonCarLib.setObjectName("pushButtonCarLib")
        self.pushButtonSupInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSupInfo.setGeometry(QtCore.QRect(370, 490, 128, 128))
        self.pushButtonSupInfo.setText("")
        self.pushButtonSupInfo.setObjectName("pushButtonSupInfo")
        self.pushButtonCarPurchase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCarPurchase.setGeometry(QtCore.QRect(630, 270, 128, 128))
        self.pushButtonCarPurchase.setText("")
        self.pushButtonCarPurchase.setObjectName("pushButtonCarPurchase")
        self.pushButtonCarSell = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCarSell.setGeometry(QtCore.QRect(630, 490, 128, 128))
        self.pushButtonCarSell.setText("")
        self.pushButtonCarSell.setObjectName("pushButtonCarSell")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(50, 220, 72, 15))
        self.labelName.setStyleSheet("font: 10pt \"新宋体\";")
        self.labelName.setObjectName("labelName")
        self.labelID = QtWidgets.QLabel(self.centralwidget)
        self.labelID.setGeometry(QtCore.QRect(50, 270, 72, 15))
        self.labelID.setStyleSheet("font: 10pt \"新宋体\";")
        self.labelID.setObjectName("labelID")
        self.labelPic = QtWidgets.QLabel(self.centralwidget)
        self.labelPic.setGeometry(QtCore.QRect(50, 40, 120, 150))
        self.labelPic.setText("")
        self.labelPic.setObjectName("labelPic")
        self.pushButtonUpdatePic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdatePic.setGeometry(QtCore.QRect(190, 160, 30, 30))
        self.pushButtonUpdatePic.setText("")
        self.pushButtonUpdatePic.setObjectName("pushButtonUpdatePic")
        operationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(operationWindow)
        self.statusbar.setObjectName("statusbar")
        operationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(operationWindow)
        QtCore.QMetaObject.connectSlotsByName(operationWindow)

    def retranslateUi(self, operationWindow):
        _translate = QtCore.QCoreApplication.translate
        operationWindow.setWindowTitle(_translate("operationWindow", "主界面"))
        self.labelCustmerInfo.setText(_translate("operationWindow", "顾客信息"))
        self.labelCustmerInfo_2.setText(_translate("operationWindow", "订单信息"))
        self.labelCustmerInfo_3.setText(_translate("operationWindow", "供应商信息"))
        self.labelCustmerInfo_4.setText(_translate("operationWindow", "汽车库存"))
        self.labelCustmerInfo_5.setText(_translate("operationWindow", "汽车订购"))
        self.labelCustmerInfo_6.setText(_translate("operationWindow", "汽车销售"))
        self.labelName.setText(_translate("operationWindow", "姓名："))
        self.labelID.setText(_translate("operationWindow", "编号："))

