# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '订单信息.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowOrderSearch(object):
    def setupUi(self, MainWindowOrderSearch):
        MainWindowOrderSearch.setObjectName("MainWindowOrderSearch")
        MainWindowOrderSearch.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowOrderSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.labelSearchType = QtWidgets.QLabel(self.centralwidget)
        self.labelSearchType.setGeometry(QtCore.QRect(90, 80, 72, 15))
        self.labelSearchType.setObjectName("labelSearchType")
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setGeometry(QtCore.QRect(590, 70, 40, 40))
        self.pushButtonSearch.setText("")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.tableWidgetResults = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetResults.setGeometry(QtCore.QRect(70, 160, 611, 231))
        self.tableWidgetResults.setObjectName("tableWidgetResults")
        self.tableWidgetResults.setColumnCount(7)
        self.tableWidgetResults.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResults.setHorizontalHeaderItem(6, item)
        self.comboBoxType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxType.setGeometry(QtCore.QRect(240, 80, 87, 22))
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.lineEditType = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditType.setGeometry(QtCore.QRect(400, 80, 113, 21))
        self.lineEditType.setObjectName("lineEditType")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 130, 72, 15))
        self.label_3.setStyleSheet("font: 10pt \"新宋体\";")
        self.label_3.setObjectName("label_3")
        MainWindowOrderSearch.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowOrderSearch)
        self.statusbar.setObjectName("statusbar")
        MainWindowOrderSearch.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowOrderSearch)
        QtCore.QMetaObject.connectSlotsByName(MainWindowOrderSearch)

    def retranslateUi(self, MainWindowOrderSearch):
        _translate = QtCore.QCoreApplication.translate
        MainWindowOrderSearch.setWindowTitle(_translate("MainWindowOrderSearch", "订单信息"))
        self.labelSearchType.setText(_translate("MainWindowOrderSearch", "查找内容"))
        item = self.tableWidgetResults.verticalHeaderItem(0)
        item.setText(_translate("MainWindowOrderSearch", "1"))
        item = self.tableWidgetResults.verticalHeaderItem(1)
        item.setText(_translate("MainWindowOrderSearch", "2"))
        item = self.tableWidgetResults.verticalHeaderItem(2)
        item.setText(_translate("MainWindowOrderSearch", "3"))
        item = self.tableWidgetResults.verticalHeaderItem(3)
        item.setText(_translate("MainWindowOrderSearch", "4"))
        item = self.tableWidgetResults.verticalHeaderItem(4)
        item.setText(_translate("MainWindowOrderSearch", "5"))
        item = self.tableWidgetResults.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowOrderSearch", "订单号"))
        item = self.tableWidgetResults.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowOrderSearch", "时间"))
        item = self.tableWidgetResults.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowOrderSearch", "员工号"))
        item = self.tableWidgetResults.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowOrderSearch", "车号"))
        item = self.tableWidgetResults.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowOrderSearch", "顾客编号"))
        item = self.tableWidgetResults.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowOrderSearch", "数量"))
        item = self.tableWidgetResults.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowOrderSearch", "价格"))
        self.comboBoxType.setItemText(0, _translate("MainWindowOrderSearch", "员工号"))
        self.comboBoxType.setItemText(1, _translate("MainWindowOrderSearch", "订单号"))
        self.comboBoxType.setItemText(2, _translate("MainWindowOrderSearch", "顾客号"))
        self.label_3.setText(_translate("MainWindowOrderSearch", "查找"))

