# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '顾客信息.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowCustmerInfo(object):
    def setupUi(self, MainWindowCustmerInfo):
        MainWindowCustmerInfo.setObjectName("MainWindowCustmerInfo")
        MainWindowCustmerInfo.resize(800, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindowCustmerInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setGeometry(QtCore.QRect(550, 50, 40, 40))
        self.pushButtonSearch.setText("")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.labelSearch = QtWidgets.QLabel(self.centralwidget)
        self.labelSearch.setGeometry(QtCore.QRect(130, 60, 72, 15))
        self.labelSearch.setObjectName("labelSearch")
        self.lineEditSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch.setGeometry(QtCore.QRect(320, 60, 113, 21))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.tableWidgetResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetResult.setGeometry(QtCore.QRect(110, 140, 531, 231))
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(4)
        self.tableWidgetResult.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(3, item)
        self.pushButtonRegister = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(150, 440, 40, 40))
        self.pushButtonRegister.setText("")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 110, 72, 15))
        self.label.setStyleSheet("font: 10pt \"新宋体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 500, 72, 15))
        self.label_2.setStyleSheet("font: 10pt \"新宋体\";")
        self.label_2.setObjectName("label_2")
        MainWindowCustmerInfo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowCustmerInfo)
        self.statusbar.setObjectName("statusbar")
        MainWindowCustmerInfo.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowCustmerInfo)
        QtCore.QMetaObject.connectSlotsByName(MainWindowCustmerInfo)

    def retranslateUi(self, MainWindowCustmerInfo):
        _translate = QtCore.QCoreApplication.translate
        MainWindowCustmerInfo.setWindowTitle(_translate("MainWindowCustmerInfo", "顾客信息"))
        self.labelSearch.setText(_translate("MainWindowCustmerInfo", "顾客姓名"))
        item = self.tableWidgetResult.verticalHeaderItem(0)
        item.setText(_translate("MainWindowCustmerInfo", "1"))
        item = self.tableWidgetResult.verticalHeaderItem(1)
        item.setText(_translate("MainWindowCustmerInfo", "2"))
        item = self.tableWidgetResult.verticalHeaderItem(2)
        item.setText(_translate("MainWindowCustmerInfo", "3"))
        item = self.tableWidgetResult.verticalHeaderItem(3)
        item.setText(_translate("MainWindowCustmerInfo", "4"))
        item = self.tableWidgetResult.verticalHeaderItem(4)
        item.setText(_translate("MainWindowCustmerInfo", "5"))
        item = self.tableWidgetResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowCustmerInfo", "编号"))
        item = self.tableWidgetResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowCustmerInfo", "姓名"))
        item = self.tableWidgetResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowCustmerInfo", "性别"))
        item = self.tableWidgetResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowCustmerInfo", "电话"))
        self.label.setText(_translate("MainWindowCustmerInfo", "查询"))
        self.label_2.setText(_translate("MainWindowCustmerInfo", "登记"))

